[package]
name = "general-request-client"
version = "0.1.0"
edition = "2021"
description = "通用请求接口"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum-starter.workspace = true
http.workspace = true
reqwest = { workspace = true, features = ["json"] }
serde.workspace = true
tap.workspace = true
url.workspace = true
