[package]
name = "qiniu_service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde.workspace = true
serde_json.workspace = true
typed-builder.workspace = true
thiserror.workspace = true
status-err = { path = "../../libs/status-err" }
futures.workspace = true
qiniu-cdn-upload.workspace = true
ceobe-qiniu-upload.workspace = true
tokio.workspace = true
qq-channel-warning = { version = "0.1.0", path = "../../middle-server/qq-channel-warning" }
redis.workspace = true
mongodb.workspace = true
persistence = { workspace = true, features = ["redis", "database-operate"] }

[dependencies.redis_global]
path = "../../global/redis_global"
