[package]
name = "ceobe-canteen-serve"
version = "0.1.1"
edition = "2021"
default-run = "server"

[[bin]]
name = "server"
path = "./src/main.rs"

[profile.release]
strip = true
lto = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["libs/*", "./models/*", "./migrate/*", "./database/*", "./macros/*"]

[features]
default = []
migrator = []
database = []
async_utils = []

[workspace.dependencies]
ahash = "0.8"
resp-result = "0.4"
axum-prehandle = "0.1"
tokio = { version = "1", features = [
    "sync",
    "rt",
    "rt-multi-thread",
    "time",
    "signal"
] }
axum-starter = { version = "0.3", features = ["logger"] }
typed-builder = "0.10"
once_cell = "1"
thiserror = "1"
sea-orm = { version = "0.9", default-features = false, features = [
    "sqlx-mysql",
    "runtime-tokio-rustls",
    "macros"
] }
reqwest = { version = "0.11", default-features = false, features = [
    "rustls-tls"
] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tap = "1.0.1"
log = "0.4.14"
urlencoding = "2.1.0"
async-trait = "0.1"
futures = "0.3"
mongodb = "2"
axum = "0.5"
chrono = "0.4"
url = { version = "2", features = ["serde"] }
sub-model = "0.2"

[dependencies]
# db
bson = { version = "2.1.0", features = ["chrono-0_4"] }
# async
async-trait = { workspace = true }
futures = { workspace = true }
pin-project = "1"
# config
figment = { version = "0.10", features = ["yaml", "json", "toml"] }
# axum
axum = { workspace = true, features = ["headers"] }
tower = { version = "0.4", features = ["limit"] }
tower-http = { version = "0.3", features = [
    "trace",
    "catch-panic",
    "set-header",
    "compression-full"
] }
axum-starter = { workspace = true }
# web
url = { workspace = true }
http = "0.2"
http-body = "0.4"
urlencoding = { workspace = true }
#encrypt
jwt = "0.16.0"
hmac = "0.12.1"
sha2 = "0.10.2"
# else
chrono = { workspace = true, features = ["serde"] }
rand = "0.8.5"
typed-builder = { workspace = true }
once_cell = { workspace = true }
thiserror = { workspace = true }
# request
reqwest = { workspace = true }
# Xss
ammonia = "3"
tap = { workspace = true }
log = { workspace = true }
md-5 = "0.10"
hex = "0.4"
ceobe-qiniu-upload = { version = "0.1.0", path = "libs/qiniu-upload" }

[dependencies.tokio]
workspace = true

[dependencies.serde]
workspace = true

[dependencies.serde_json]
workspace = true

[dependencies.crypto_str]
path = "./libs/crypto_str"
features = ["serde", "bcrypt"]

[dependencies.range-limit]
path = "./libs/range-limit"

[dependencies.logger]
path = "./libs/logger"

[dependencies.status-err]
path = "./libs/status-err"

[dependencies.resp-result]
workspace = true

[dependencies.axum-prehandle]
workspace = true

[dependencies.checker]
path = "./libs/checker"

[dependencies.orm-migrate]
package = "migration"
path = "./migrate/sql-migration"

[dependencies.mongo-migration]
path = "./migrate/mongo-migration"

[dependencies.modify-cache]
path = "./libs/modify-cache"

[dependencies.database_traits]
path = "./database/database_traits"

[dependencies.page_size]
path = "./libs/page_size"
