[package]
name = "ceobe-canteen-serve"
version = "0.1.0"
edition = "2021"
default-run = "server"

[[bin]]
name = "server"
path = "./src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["libs/*", "./models/*", "./migrate/*", "./database/*", "./macros/*"]

[features]
default = []
migrator = []
database = []
async_utils = []

[dependencies]
# db
bson = { version = "2.1.0", features = ["chrono-0_4"] }
# async
async-trait = "0.1"
futures = "0.3"
pin-project = "1"
# config
figment = { version = "0.10", features = ["yaml", "json", "toml"] }
# axum
axum = { version = "0.5", features = ["headers"] }
tower = { version = "0.4", features = ["limit"] }
tower-http = { version = "0.3", features = [
    "trace",
    "catch-panic",
    "set-header",
    "compression-full"
] }
# web
url = "2.2.2"
http = "0.2"
http-body = "0.4"
urlencoding = "2.1.0"
log = "0.4.14"
#encrypt
jwt = "0.16.0"
hmac = "0.12.1"
sha2 = "0.10.2"
# else
rust-crypto = "0.2"
chrono = { version = "0.4", features = ["serde"] }
rand = "0.8.5"
typed-builder = "0.10"
once_cell = "1"
thiserror = "1"
# request
reqwest = "0.11"
# Xss
ammonia = "3"

[dependencies.tokio]
version = "1.15.0"
features = ["sync", "rt", "rt-multi-thread", "time", "signal"]

[dependencies.serde]
version = "1.0.133"
features = ["derive"]

[dependencies.serde_json]
version = "1.0.75"

[dependencies.crypto_str]
path = "./libs/crypto_str"
features = ["serde", "bcrypt"]

[dependencies.range-limit]
path = "./libs/range-limit"

[dependencies.logger]
path = "./libs/logger"

[dependencies.status-err]
path = "./libs/status-err"

[dependencies.resp-result]
version = "0.4.1"

[dependencies.axum-prehandle]
version = "0.1.2"

[dependencies.checker]
path = "./libs/checker"

[dependencies.time-usage]
path = "./libs/time-usage"

[dependencies.orm-migrate]
package = "migration"
path = "./migrate/sql-migration"

[dependencies.mongo-migration]
path = "./migrate/mongo-migration"

[dependencies.modify-cache]
path = "./libs/modify-cache"

[dependencies.database_initial]
path = "./database/database_initial"