//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "mansion")]
pub struct Model {
    #[sea_orm(primary_key, unique)]
    pub id: i64,
    pub mid: i32,
    pub sub_mid: i32,
    pub description: String,
    pub link: String,
    pub fraction: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::daily_mansion::Entity")]
    DailyMansion,
}

impl Related<super::daily_mansion::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DailyMansion.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
