//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use super::sea_orm_active_enums::PredictLevel;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "mansion_info")]
pub struct Model {
    #[sea_orm(primary_key, unique)]
    pub id: i64,
    pub eid: i64,
    pub predict_level: PredictLevel,
    #[sea_orm(column_type = "Text")]
    pub info: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::each_mansion::Entity",
        from = "Column::Eid",
        to = "super::each_mansion::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    EachMansion,
}

impl Related<super::each_mansion::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EachMansion.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
