//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

pub use super::each_mansion::Entity as EachMansion;
pub use super::mansion::Entity as Mansion;
pub use super::mansion_info::Entity as MansionInfo;
pub use super::seaql_migrations::Entity as SeaqlMigrations;
pub use super::users::Entity as Users;
