//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

pub use super::daily_mansion::Entity as DailyMansion;
pub use super::mansion::Entity as Mansion;
pub use super::mansion_info::Entity as MansionInfo;
pub use super::seaql_migrations::Entity as SeaqlMigrations;
