//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "predict_level")]
pub enum PredictLevel {
    #[sea_orm(string_value = "false")]
    False,
    #[sea_orm(string_value = "unknown")]
    Unknown,
    #[sea_orm(string_value = "true")]
    True,
}
