[package]
name = "qiniu-cdn-upload"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
axum = { workspace = true }
ceobe-qiniu-upload = { workspace = true }
futures = { workspace = true }
mime = "0.3.16"
