//! SeaORM Entity. Generated by sea-orm-codegen 0.4.1

pub use super::each_mansion::Entity as EachMansion;
pub use super::mansion::Entity as Mansion;
pub use super::mansion_info::Entity as MansionInfo;
