[package]
name = "mongo-migration"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
mongodb = "2"
async-trait="0.1"
serde="1"
dashmap="5"
typed-builder="0.10"

[dependencies.mongo-models]
path = "../../models/mongo-models"
