[package]
name = "select-only-model-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
darling = "0.14"
heck = "0.4.1"
quote = "1"
syn = "1"

[dev-dependencies]
sql-models = { path = "../../models/sql-models" }
sql_connection = { path = "../../database/sql_connection" }
