[package]
name = "mongo-models"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
mongodb = "2"
chrono = "0.4"
typed-builder = "0.10"

[dependencies.sub-model]
version = "0.1"

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.checker]
path = "../../libs/checker"

[dependencies.range-limit]
path = "../../libs/range-limit"

[dependencies.mongo_connection]
path = "../../database/mongo_connection"

[dependencies.status-err]
path = "../../libs/status-err"
