[package]
name = "mongo-models"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
mongodb = { version =  "2",features = ["bson-chrono-0_4"]}
chrono = { version = "0.4", features = ["serde"] }
typed-builder = "0.10"
thiserror = "1"
futures = "0.3"
log = "0.4"
tap = "1"
url = { version = "2", features = ["serde"] }
modify-cache = {path = "../../libs/modify-cache"}
[dependencies.sub-model]
version = "0.1"

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.checker]
path = "../../libs/checker"

[dependencies.range-limit]
path = "../../libs/range-limit"

[dependencies.mongo_connection]
path = "../../database/mongo_connection"

[dependencies.status-err]
path = "../../libs/status-err"

[dependencies.futures-util]
version = "0.3"
features = ["std", "sink"]
