[package]
name = "persistence"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
prelude = ["db-prelude",
    "model-admin",
    "model-bakery",
    "model-ceobe-cookie",
    "model-ceobe-operate",
    "model-ceobe-user",
    "model-fetcher",
    "mongodb",
    "mysql",
    "database-connect",
    "database-operate"]

mongodb = ["mongo-connect"]
redis = ["redis-connect"]
mysql = ["sql-connect"]
mongo-migrate = ["mongo-migration"]
mysql-migrate = ["sql-migration"]

model-admin = ["admin", "mysql", "database-operate", "sql-models"]
model-bakery = ["bakery", "mongodb", "database-operate", "mongo-models"]
model-ceobe-cookie = ["ceobe-cookie", "mysql", "mongodb", "database-operate", "sql-models", "mongo-models"]
model-ceobe-operate = ["ceobe-operate", "mongodb", "mysql", "database-operate", "sql-models", "mongo-models"]
model-ceobe-user = ["ceobe-user", "mongodb", "database-operate", "mongo-models"]
model-fetcher = ["fetcher", "mysql", "database-operate", "sql-models"]

database-connect = ["traits/initial"]
database-operate = ["traits/get-connect", "abstract"]

[dependencies]
abstract = { version = "0.1.0", path = "../database/abstract_database", package = "abstract_database", optional = true }
admin = { version = "0.1.0", path = "../dao/admin", optional = true }
bakery = { version = "0.1.0", path = "../dao/bakery", optional = true }
ceobe-cookie = { version = "0.1.0", path = "../dao/ceobe-cookie", optional = true }
ceobe-operate = { version = "0.1.0", path = "../dao/ceobe-operate", optional = true }
ceobe-user = { version = "0.1.0", path = "../dao/ceobe-user", optional = true }
db-prelude = { version = "0.1.0", path = "../database/db-ops-prelude", package = "db-ops-prelude", optional = true }
fetcher = { version = "0.1.0", path = "../dao/fetcher", optional = true }
mongo-connect = { version = "0.1.0", path = "../database/mongo_connection", package = "mongo_connection", optional = true }
mongo-migration = { version = "0.1.0", path = "../migrate/mongo-migration", optional = true }
mongo-models = { version = "0.1.0", path = "../models/mongo-models", optional = true }
redis-connect = { version = "0.1.0", path = "../database/redis_connection", package = "redis_connection", optional = true }
sql-connect = { version = "0.1.0", path = "../database/sql_connection", package = "sql_connection", optional = true }
sql-migration = { version = "0.1.0", path = "../migrate/sql-migration", package = "migration", optional = true }
sql-models = { version = "0.1.0", path = "../models/sql-models", optional = true }
traits = { version = "0.1.0", path = "../database/database_traits", package = "database_traits", optional = true }



