[package]
name = "persistence"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
help-crates=["db-prelude","db-prelude/help-crates-only"]
prelude = ["db-prelude",
    "model-admin",
    "model-bakery",
    "model-ceobe-cookie",
    "model-ceobe-operate",
    "model-ceobe-user",
    "model-fetcher",
    "mongodb",
    "mysql",
    "redis",
    "database-connect",
    "database-operate"]

mongodb = ["mongo-connect"]
redis = ["redis-connect"]
mysql = ["sql-connect"]

migrate = ["mongo-migrate","mysql-migrate"]
mongo-migrate = ["mongo-migration"]
mysql-migrate = ["sql-migration"]

model-admin = ["dao-admin", "mysql", "database-operate", "sql-models"]
model-bakery = ["dao-bakery", "mongodb", "database-operate", "mongo-models"]
model-ceobe-cookie = ["dao-ceobe-cookie", "mysql", "mongodb", "database-operate", "sql-models", "mongo-models"]
model-ceobe-operate = ["dao-ceobe-operate", "mongodb", "mysql", "database-operate", "sql-models", "mongo-models"]
model-ceobe-user = ["dao-ceobe-user", "mongodb", "database-operate", "mongo-models"]
model-fetcher = ["dao-fetcher", "mysql", "database-operate", "sql-models"]

database-connect = ["traits","traits/initial"]
database-operate = ["traits","traits/get-connect", "abstract"]

[dependencies]
abstract = { version = "0.1.0", path = "../database/abstract_database", package = "abstract_database", optional = true }
dao-admin = { version = "0.1.0", path = "../dao/admin", optional = true ,package = "admin"}
dao-bakery = { version = "0.1.0", path = "../dao/bakery", optional = true ,package = "bakery"}
dao-ceobe-cookie = { version = "0.1.0", path = "../dao/ceobe-cookie", optional = true ,package = "ceobe-cookie"}
dao-ceobe-operate = { version = "0.1.0", path = "../dao/ceobe-operate", optional = true ,package = "ceobe-operate"}
dao-ceobe-user = { version = "0.1.0", path = "../dao/ceobe-user", optional = true, package = "ceobe-user"}
db-prelude = { version = "0.1.0", path = "../database/db-ops-prelude", package = "db-ops-prelude", optional = true }
dao-fetcher = { version = "0.1.0", path = "../dao/fetcher", optional = true ,package = "fetcher"}
mongo-connect = { version = "0.1.0", path = "../database/mongo_connection", package = "mongo_connection", optional = true }
mongo-migration = { version = "0.1.0", path = "../migrate/mongo-migration", optional = true }
mongo-models = { version = "0.1.0", path = "../models/mongo-models", optional = true }
redis-connect = { version = "0.1.0", path = "../database/redis_connection", package = "redis_connection", optional = true }
sql-connect = { version = "0.1.0", path = "../database/sql_connection", package = "sql_connection", optional = true }
sql-migration = { version = "0.1.0", path = "../migrate/sql-migration", package = "migration", optional = true }
sql-models = { version = "0.1.0", path = "../models/sql-models", optional = true }
traits = { version = "0.1.0", path = "../database/database_traits", package = "database_traits", optional = true }



