[package]
name = "mob-push-logic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fetcher.workspace = true
mob_push = "0.2.1"
