[package]
name = "db-ops-prelude"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono.workspace = true
database_traits = { version = "0.1.0", path = "../database_traits" }
futures.workspace = true
mongo-models = { version = "0.1.0", path = "../../models/mongo-models" }
smallstr.workspace = true
smallvec.workspace = true
sql-models = { version = "0.1.0", path = "../../models/sql-models" }
status-err = { version = "0.1.0", path = "../../../libs/status-err" }
tap.workspace = true
thiserror.workspace = true
tracing.workspace = true
bool_or.workspace = true
mysql_func.workspace = true
time-utils = { workspace = true, features = ["with-sea-orm", "with-mongo"] }
mongo_connection = { version = "0.1.0", path = "../mongo_connection" }
sql_connection = { version = "0.1.0", path = "../sql_connection" }
