[package]
name = "release_version_service"
version = "0.1.0"
edition = "2021"

[dependencies]
persistence = { workspace = true, features = ["model-ceobe-operate", "help-crates"] }
semver = "1.0.23"
serve_utils = { version = "0.1.0", path = "../../../libs/serve_utils" }
serde = { version = "1.0.201", features = ["derive"] }
thiserror.workspace = true
status-err.workspace = true
http.workspace = true
axum-resp-result.workspace = true
tracing.workspace = true