[package]
name = "sql-models"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
once_cell = "1"
regex = "1"
thiserror = "1"
typed-builder = "0.10"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
sub-model = "0.1"
serde = { version = "1", features = ["derive"] }
url = { version = "2", features = ["serde"] }
sea-orm = { version = "0.9", default-features = false, features = [
    "sqlx-mysql",
    "runtime-tokio-rustls",
    "macros",
    "with-chrono"
] }
checker = { path = "../../libs/checker" }
range-limit = { path = "../../libs/range-limit" }
sql_connection = { path = "../../database/sql_connection" }
status-err = { path = "../../libs/status-err" }
modify-cache = {path = "../../libs/modify-cache"}

[dev-dependencies]
tokio = { version = "1", features = ["test-util", "macros"] }
