[package]
name = "mob-push"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum-starter.workspace = true
ceobe-user.workspace = true
fetcher.workspace = true
general-request-client.workspace = true
mob_push = "0.2.1"
mongo-models = { version = "0.1.0", path = "../../models/mongo-models" }
reqwest.workspace = true
sql-models = { version = "0.1.0", path = "../../models/sql-models" }
status-err = { version = "0.1.0", path = "../../libs/status-err" }
thiserror.workspace = true
tokio.workspace = true
url.workspace = true
uuid.workspace = true
