//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

pub use super::each_mansion::Entity as EachMansion;
pub use super::inner_mansion::Entity as InnerMansion;
pub use super::mansion::Entity as Mansion;
pub use super::seaql_migrations::Entity as SeaqlMigrations;
