[package]
name = "mob-push-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum-core.workspace = true
axum-starter.workspace = true
bytes = "1.4.0"
general-request-client.workspace = true
md-5 = "0.10.5"
secrecy.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
typed-builder.workspace = true
url.workspace = true
urlencoding.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util", "macros"] }
