[package]
name = "qq-channel-warning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.9.1"

[build-dependencies]
tonic-build = "0.9.1"
