[package]
name = "qq-channel-warning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum.workspace = true
axum-starter.workspace = true
http.workspace = true
prost = "0.11.9"
resp-result.workspace = true
status-err = { version = "0.1.0", path = "../../libs/status-err" }
thiserror.workspace = true
tonic = "0.9.1"
typed-builder = "0.14.0"
url.workspace = true

[build-dependencies]
tonic-build = "0.9.1"

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
