[package]
name = "mongo-models"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
mongodb = { workspace = true, features = ["bson-chrono-0_4"] }
chrono = { workspace = true, features = ["serde"] }
typed-builder = { workspace = true }
thiserror = { workspace = true }
futures = { workspace = true }
tap = { workspace = true }
url = { workspace = true }
tracing = { workspace = true }
modify-cache = { path = "../../../libs/modify-cache" }
bool_or.workspace = true
serde_json.workspace = true
semver = { version = "1.0.23", features = ["serde"] }

[dependencies.sub-model]
workspace = true

[dependencies.serde]
workspace = true

[dependencies.checker]
path = "../../../libs/checker"

[dependencies.range-limit]
path = "../../../libs/range-limit"

[dependencies.mongo_connection]
path = "../../database/mongo_connection"

[dependencies.status-err]
path = "../../../libs/status-err"

