# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Docker build CI
on:
  push:
    branches: [ master ]
    tags:
      - "v*"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      -
        name: Build and push release
        uses: docker/build-push-action@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          context: .
          push: true
          tags: ceobecanteen/ceobe-canteen-server:$TAG_NAME
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - 
        name: Build and push latest
        uses: docker/build-push-action@v2
        if: "!startsWith(github.ref, 'refs/tags/v')"
        with:
          context: .
          push: true
          tags: ceobecanteen/ceobe-canteen-server
          cache-from: type=gha
          cache-to: type=gha,mode=max

