name: check CI

on:
  pull_request:
    branches: [master, deploy]
    paths-ignore:
      - "**.md"
      - "**.py"
      - "**.json"

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Rust toolchain Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.70.0
          components: clippy
          default: true
      - name: Rust toolchain Nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.73.0-nightly
          components: rustfmt
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - run: ls -l ./assets/proto/protos
      - run: cargo +nightly fmt --check
      - run: cargo clippy
