name: check CI

on:
  pull_request:
    branches: [ master, deploy ]
    paths-ignore:
      - "**.md"
      - "**.py"
      - "**.json"

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Rust toolchain Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.65.0
          components: clippy
          default: true
      - name: Rust toolchain Nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components:  rustfmt
      - run: cargo +nightly fmt --check
      - run: cargo clippy
