name: check CI

on:
  pull_request:
    branches: [ master, deploy ]
    paths-ignore:
      - "**.md"
      - "**.py"
      - "**.json"

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy, rustfmt
          default: true
      - run: cargo check
      - run: cargo fmt --check
      - run: cargo clippy
