[package]
name = "request-clients"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
axum-core = { workspace = true }
axum-starter = { workspace = true }
bytes = "1.3.0"
futures = { workspace = true }
http = { workspace = true }
reqwest = { workspace = true }
sql-models = { version = "0.1.0", path = "../../persistence/models/sql-models" }
status-err = { version = "0.1.0", path = "../../libs/status-err" }
thiserror = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
